#!/usr/bin/with-contenv sh
# Set current user in nss_wrapper
#USER_ID=$(id -u)
#GROUP_ID=$(id -g)
echo "Setting up to start tigervnc for user $USER_NAME ..."

#if [ x"$USER_ID" != x"0" ]; then
#
#    NSS_WRAPPER_PASSWD=/tmp/passwd
#    NSS_WRAPPER_GROUP=/etc/group

#    cat /etc/passwd > $NSS_WRAPPER_PASSWD

#    echo "default:x:${USER_ID}:${GROUP_ID}:Default Application User:${HOME}:/bin/bash" >> $NSS_WRAPPER_PASSWD

#    export NSS_WRAPPER_PASSWD
#    export NSS_WRAPPER_GROUP

#    if [ -r /usr/lib/libnss_wrapper.so ]; then
#        LD_PRELOAD=/usr/lib/libnss_wrapper.so
#    elif [ -r /usr/lib64/libnss_wrapper.so ]; then
#        LD_PRELOAD=/usr/lib64/libnss_wrapper.so
#    else
#        echo "no libnss_wrapper.so installed!"
#        exit 1
#    fi
#    echo "nss_wrapper location: $LD_PRELOAD"
#    export LD_PRELOAD
#fi

echo "Starting tigervnc for user $USER_NAME on DISPLAY $DISPLAY ..."
s6-setuidgid $USER_NAME vncserver -fg $DISPLAY -depth $VNC_COL_DEPTH -geometry $VNC_RESOLUTION > /tmp/no_vnc_startup.log
