#!/usr/bin/with-contenv sh

echo "Starting tigervnc for user $USER_NAME on DISPLAY $DISPLAY ..."
s6-setuidgid $USER_NAME vncserver -fg $DISPLAY -depth $VNC_COL_DEPTH -geometry $VNC_RESOLUTION > /tmp/no_vnc_startup.log
